# Site settings
title: We are on the road together
description: "The soul of every faith is comforted and satisfied on the road"
url: "https://www.qwfys.com/monochrome/"
author:
  name: "听风者"
  email: "qwfys200@qq.com"
  url: "https://github.com/qwfys"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: true
custom_nav_footer: true
reverse: false
